Repository potenday-project/Color_On_Me_BE, pull requests merged in 2023-06, with the labels that each got.

#1 feat/DB : 몽구스 연결
  package-lock.json
  package.json
  src/app.module.ts
Labels: enhancement

#2 Chore
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app/app.controller.ts
  src/app/app.module.ts
  src/app/app.service.ts
  src/domain/personal-color/controller/personal-color.controller.ts
  src/domain/personal-color/model/personal-color.model.ts
  src/domain/personal-color/personal-color.module.ts
  src/domain/personal-color/service/personal-color.service.ts
  src/domain/user/controller/user.controller.ts
  src/domain/user/model/user.model.ts
  src/domain/user/service/user.service.ts
  src/domain/user/user.module.ts
  src/main.ts
  test/app.e2e-spec.ts
Labels: chore

#4 Feat/user login
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/app/app.module.ts
  src/domain/auth/auth.controller.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/auth/guard/jwt-access-token-auth.guard.ts
  src/domain/auth/guard/jwt-refresh-token-auth.guard.ts
  src/domain/auth/guard/naver-auth.guard.ts
  src/domain/auth/strategy/jwt-access-token.strategy.ts
  src/domain/auth/strategy/jwt-refresh-token.strategy.ts
  src/domain/auth/strategy/jwt-social-naver.strategy.ts
  src/domain/common/decorators/get-current-user-id.decorator.ts
  src/domain/common/decorators/get-current-user.decorator.ts
  src/domain/config/config.module.ts
  src/domain/config/config.service.ts
  src/domain/config/env-config.ts
  src/domain/user/model/user.model.ts
  src/domain/user/service/user.service.ts
  src/domain/user/user.module.ts
  src/main.ts
Labels: enhancement

#6 fix: 쿠키 정책 변경으로 인한 수정
  src/domain/auth/auth.controller.ts
Labels: fix

#7 Feat/p color
  src/app/app.module.ts
  src/domain/personal-color/controller/personal-color.controller.ts
  src/domain/personal-color/model/personal-color.model.ts
  src/domain/personal-color/personal-color.module.ts
  src/domain/personal-color/service/personal-color.service.ts
Labels: enhancement

#8 Hot fix/jwt
  package-lock.json
  package.json
  src/domain/auth/auth.service.ts
  src/domain/auth/strategy/jwt-access-token.strategy.ts
  src/domain/auth/strategy/jwt-refresh-token.strategy.ts
  src/main.ts
Labels: fix

#9 Feat/apply jwt policy
  src/domain/personal-color/controller/personal-color.controller.ts
  src/domain/user/controller/user.controller.ts
  src/domain/user/service/user.service.ts
Labels: enhancement

#10 Fix/user model
  src/domain/auth/strategy/jwt-social-naver.strategy.ts
  src/domain/user/model/user.model.ts
  src/domain/user/service/user.service.ts
Labels: fix

#11 Fix/personal color
  src/domain/personal-color/controller/personal-color.controller.ts
  src/domain/personal-color/personal-color.module.ts
  src/domain/personal-color/service/personal-color.service.ts
Labels: fix

#12 feat: user/me api 작성
  src/domain/auth/auth.controller.ts
Labels: fix

#13 fix: user/me 동작 수정
  src/domain/auth/auth.controller.ts
Labels: fix

#16 Feat/sign up
  package-lock.json
  package.json
  src/domain/auth/auth.controller.ts
  src/domain/auth/auth.module.ts
  src/domain/auth/auth.service.ts
  src/domain/auth/dto/signup.dto.ts
  src/domain/user/model/user.model.ts
Labels: enhancement

#17 feat: 퍼스널컬러 데이터 넣는 api
  scripts/personal-color_Data.json
  src/domain/personal-color/controller/personal-color.controller.ts
  src/domain/personal-color/service/personal-color.service.ts
Labels: enhancement

#18 Feat/login
  src/domain/auth/auth.controller.ts
  src/domain/auth/auth.service.ts
  src/domain/auth/dto/check-email.dto.ts
  src/domain/auth/dto/login.dto.ts
  src/domain/auth/dto/signup.dto.ts
  src/domain/auth/strategy/jwt-social-kakao.strategy.ts
  src/domain/auth/strategy/jwt-social-naver.strategy.ts
  src/domain/user/model/user.model.ts
  src/domain/user/service/user.service.ts
  src/main.ts
Labels: enhancement

#19 fix: 빠진 색상 데이터 추가
  scripts/personal-color_Data.json
Labels: fix

#20 feat: CI/CD Deploy to NCP
  .github/workflows/ncp.yml
Labels: enhancement
